package com.local.project.enumeration;

public enum ERole {

	ROLE_ADMIN,
    ROLE_SUBADMIN,
    ROLE_DEPARTMENT_HOD,
    ROLE_DEPARTMENT_REPORTEE,
    ROLE_CLIENT_USER,
    ROLE_RELATION_HEAD,
    ROLE_RELATION_TEAM,
    ROLE_LIASION_HEAD,   
    ROLE_LIASION_TEAM_N,
    ROLE_LIASION_TEAM_S,
    ROLE_OPS_HEAD,
//  ROLE_PC,
//  ROLE_LC,
//  ROLE_FC,
    ROLE_OPS_MANAGER,
	ROLE_OPS_PF_TEAM,
	ROLE_OPS_ESI_TEAM,
	ROLE_OPS_LC_TEAM,
	ROLE_OPS_CLRA_TEAM,
	ROLE_OPS_LWT_TEAM,
	
	ROLE_REGISTRATION_HEAD,
	ROLE_REGISTRATION_TEAM,
	ROLE_NOTICES_HEAD,
	ROLE_NOTICES_TEAM
}
